services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: nvidia-smi
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
